[project]
name = "fsds-ecommerce"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.3",
    "mlflow>=3.13.0",
    "pandas>=2.3.3",
    "pyarrow>=24.0.0",
    "pyspark>=4.1.2",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "python-dotenv>=1.2.2",
    "ruff>=0.15.15",
    "scikit-learn>=1.9.0",
    "uvicorn>=0.48.0",
]
