packages:
  - org.apache.hadoop:hadoop-aws:3.4.2
  - com.amazonaws:aws-java-sdk-bundle:1.12.367
  - io.delta:delta-spark_2.13:4.1.0

minio:
  endpoint: http://localhost:9000
  access_key: minio_access_key
  secret_key: minio_secret_key

layers:
  bronze:
    local_path: ./b_schema_pipelines/delta_lake_data/bronze
    bucket: bronze-data
    prefix: bronze
  silver:
    local_path: ./b_schema_pipelines/delta_lake_data/silver
    bucket: silver-data
    prefix: silver
  gold:
    local_path: ./b_schema_pipelines/delta_lake_data/gold
    bucket: gold-data
    prefix: gold
